
-- Solution joining in the Airport Lookup Table --
-- TRY TO GET THIS QUERY UNDER 1.1 SECOND FOR PERFORMANCE --
with a as(
select DEST_AIRPORT_ID, ORIGIN_AIRPORT_ID, SUM(CAST([PASSENGERS] as int)) as [ARRIVING PASSENGERS]
from [T100_SEGMENT_ALL_CARRIER_2023]
where CAST([Passengers] as INT) > 0 and CAST([DEPARTURES_PERFORMED] AS int) > 0
group by DEST_AIRPORT_ID, ORIGIN_AIRPORT_ID),

totals as (
select a.[DEST_AIRPORT_ID], 
B.[DESCRIPTION] as [DEST AIRPORT NAME], 
a.[ORIGIN_AIRPORT_ID], 
c.[DESCRIPTION] as [ORIGIN AIRPORT NAME],
a.[ARRIVING PASSENGERS],
ROW_NUMBER () over (partition by a.[DEST_AIRPORT_ID] order by a.[ARRIVING PASSENGERS] DESC) as [ORIGIN AIRPORT RANKING]
from a

left join T100_AIRPORT_CODE_LOOKUP_2023 b
on a.DEST_AIRPORT_ID = b.[CODE]

left join T100_AIRPORT_CODE_LOOKUP_2023 c
on a.ORIGIN_AIRPORT_ID = c.[CODE]

where a.[DEST_AIRPORT_ID] = (select CODE from T100_AIRPORT_CODE_LOOKUP_2023 where DESCRIPTION = 'Albuquerque, NM: Albuquerque International Sunport')),

carrier_dump as (

select DEST_AIRPORT_ID, 
ORIGIN_AIRPORT_ID,
UNIQUE_CARRIER_NAME, 
SUM(CAST([PASSENGERS] AS INT)) as [CARRIER TOTAL PASSENGERS]
from [T100_SEGMENT_ALL_CARRIER_2023] x

left join T100_AIRPORT_CODE_LOOKUP_2023 y
on DEST_AIRPORT_ID = y.[CODE]

left join T100_AIRPORT_CODE_LOOKUP_2023 z
on ORIGIN_AIRPORT_ID = z.[CODE]

where CAST([Passengers] as INT) > 0 and CAST([DEPARTURES_PERFORMED] AS int) > 0
group by DEST_AIRPORT_ID, ORIGIN_AIRPORT_ID, UNIQUE_CARRIER_NAME

)


select t.[DEST AIRPORT NAME], t.[ORIGIN AIRPORT NAME], t.[ARRIVING PASSENGERS],
CASE WHEN (CAST([CARRIER TOTAL PASSENGERS] as FLOAT) / CAST([ARRIVING PASSENGERS] as float)) <= 0.05 then 'Other Carriers' else c.[UNIQUE_CARRIER_NAME] END as [UNIQUE CARRIER SIMPLIFIED],
c.[UNIQUE_CARRIER_NAME],
c.[CARRIER TOTAL PASSENGERS]
from totals t
inner join carrier_dump c
on t.DEST_AIRPORT_ID = c.DEST_AIRPORT_ID and t.ORIGIN_AIRPORT_ID = c.ORIGIN_AIRPORT_ID
where CAST(t.[ORIGIN AIRPORT RANKING] as INT) <= 10
