---- Passenger Summary Table Creation Script ----
-- CREATE TABLE [T100_PASSENGER_UTILIZATION_SUMMARY] AS
-- 
-- with routes as (
-- 
-- select [UNIQUE_CARRIER_NAME],
-- [MONTH],
-- [AIRCRAFT_TYPE],
-- [ORIGIN], [ORIGIN_CITY_NAME],
-- [DEST], [DEST_CITY_NAME],
-- CAST([PASSENGERS] AS INT) AS [T_PASSENGERS],
-- CAST([SEATS] AS INT) AS [T_SEATS],
-- CAST([DEPARTURES_PERFORMED] AS INT) AS [T_DEPARTURES],
-- [ORIGIN] || '_' || [ORIGIN_CITY_NAME] || '_' || [DEST] || '_' || [DEST_CITY_NAME] as [ROUTE_CONCAT]
-- from T100_SEGMENT_ALL_CARRIER_2023 
-- where CAST([PASSENGERS] AS INT) > 0 AND CAST([DEPARTURES_PERFORMED] AS INT) > 0)
-- 
-- select a.[UNIQUE_CARRIER_NAME],
-- a.[MONTH],
-- c.[MONTH_NAME_SHORT],
-- b.[DESCRIPTION] as [AIRCRAFT_DESC],
-- a.[AIRCRAFT_TYPE],
-- COUNT(DISTINCT a.[ROUTE_CONCAT]) AS [NUMBER_OF_ROUTES],
-- SUM(a.[T_PASSENGERS]) as [TOTAL_PASSENGERS],
-- SUM(a.[T_SEATS]) as [TOTAL_SEATS],
-- SUM(a.[T_DEPARTURES]) as [TOTAL_DEPARTURES]
-- 
-- FROM routes a
-- left join T100_SEGMENT_AIRCRAFT_TYPE_LOOKUP_2023 b
-- on a.[AIRCRAFT_TYPE] = b.[CODE]
-- left join [MONTHS_LOOKUP] c
-- on a.[MONTH] = c.[MONTH]
-- GROUP BY a.[UNIQUE_CARRIER_NAME], a.[MONTH], C.[MONTH_NAME_SHORT], b.[DESCRIPTION], a.[AIRCRAFT_TYPE]
-- ORDER BY a.[UNIQUE_CARRIER_NAME] ASC, CAST(a.[MONTH] AS INT) ASC;

-- DROP TABLE COMMAND
-- DROP TABLE [T100_PASSENGER_UTILIZATION_SUMMARY]

-- Truncate and Load --
DELETE FROM [T100_PASSENGER_UTILIZATION_SUMMARY];

with routes as (

select [UNIQUE_CARRIER_NAME],
[MONTH],
[AIRCRAFT_TYPE],
[ORIGIN], [ORIGIN_CITY_NAME],
[DEST], [DEST_CITY_NAME],
CAST([PASSENGERS] AS INT) AS [T_PASSENGERS],
CAST([SEATS] AS INT) AS [T_SEATS],
CAST([DEPARTURES_PERFORMED] AS INT) AS [T_DEPARTURES],
[ORIGIN] || '_' || [ORIGIN_CITY_NAME] || '_' || [DEST] || '_' || [DEST_CITY_NAME] as [ROUTE_CONCAT]
from T100_SEGMENT_ALL_CARRIER_2023 
where CAST([PASSENGERS] AS INT) > 0 AND CAST([DEPARTURES_PERFORMED] AS INT) > 0)

INSERT INTO [T100_PASSENGER_UTILIZATION_SUMMARY]

select a.[UNIQUE_CARRIER_NAME],
a.[MONTH],
c.[MONTH_NAME_SHORT],
b.[DESCRIPTION] as [AIRCRAFT_DESC],
a.[AIRCRAFT_TYPE],
COUNT(DISTINCT a.[ROUTE_CONCAT]) AS [NUMBER_OF_ROUTES],
SUM(a.[T_PASSENGERS]) as [TOTAL_PASSENGERS],
SUM(a.[T_SEATS]) as [TOTAL_SEATS],
SUM(a.[T_DEPARTURES]) as [TOTAL_DEPARTURES]

FROM routes a
left join T100_SEGMENT_AIRCRAFT_TYPE_LOOKUP_2023 b
on a.[AIRCRAFT_TYPE] = b.[CODE]
left join [MONTHS_LOOKUP]
on a.[MONTH] = c.[MONTH]
GROUP BY a.[UNIQUE_CARRIER_NAME], a.[MONTH], b.[DESCRIPTION], a.[AIRCRAFT_TYPE]
ORDER BY a.[UNIQUE_CARRIER_NAME] ASC, CAST(a.[MONTH] AS INT) ASC;

