select * from T100_SEGMENT_ALL_CARRIER_2023_AIRPORTS_LOOKUP
where UNIQUE_CARRIER_NAME like '%Porter%'

select UNIQUE_CARRIER_NAME,
DEST_AIRPORT_NAME,
DEST || ': ' || DEST_CITY_NAME as [DEST_CODE_CITY],
ORIGIN_AIRPORT_NAME,
ORIGIN || ': ' || ORIGIN_CITY_NAME as [ORIGIN_CODE_CITY],
SUM(CAST(PASSENGERS AS INT)) as [TOTAL_PASSENGERS],
SUM(CAST(SEATS AS INT)) as [TOTAL_SEATS]

from T100_SEGMENT_ALL_CARRIER_2023_AIRPORTS_LOOKUP

where DEST_AIRPORT_NAME != ORIGIN_AIRPORT_NAME
and CAST(PASSENGERS as INT) > 0
and CAST(DEPARTURES_PERFORMED as INT) > 0
and UNIQUE_CARRIER_NAME like '%Porter%'

group by
UNIQUE_CARRIER_NAME,
DEST_AIRPORT_NAME,
DEST || ': ' || DEST_CITY_NAME,
ORIGIN_AIRPORT_NAME,
ORIGIN || ': ' || ORIGIN_CITY_NAME 


-- Main Script to provide top 10 routes for carriers --
-- Will show seats, passengers, and Pct Utilization --
with main_grouping as (
select UNIQUE_CARRIER_NAME,
DEST_AIRPORT_NAME,
DEST || ': ' || DEST_CITY_NAME as [DEST_CODE_CITY],
ORIGIN_AIRPORT_NAME,
ORIGIN || ': ' || ORIGIN_CITY_NAME as [ORIGIN_CODE_CITY],
SUM(CAST(PASSENGERS AS INT)) as [TOTAL_PASSENGERS],
SUM(CAST(SEATS AS INT)) as [TOTAL_SEATS]

from T100_SEGMENT_ALL_CARRIER_2023_AIRPORTS_LOOKUP

where DEST_AIRPORT_NAME != ORIGIN_AIRPORT_NAME
and CAST(PASSENGERS as INT) > 0
and CAST(DEPARTURES_PERFORMED as INT) > 0

group by
UNIQUE_CARRIER_NAME,
DEST_AIRPORT_NAME,
DEST || ': ' || DEST_CITY_NAME,
ORIGIN_AIRPORT_NAME,
ORIGIN || ': ' || ORIGIN_CITY_NAME 
),


-- Lynx Air Calgary & Orlando -- 
-- Orlando to Calgary: 1605 Passengers, 3024 Seats --
-- Calgary to ORlando: 1408 Passengers, 3024 Seats --

sorting as (
select *,
CASE 
    when DEST_CODE_CITY > ORIGIN_CODE_CITY then DEST_CODE_CITY || ' & ' || ORIGIN_CODE_CITY
    when ORIGIN_CODE_CITY > DEST_CODE_CITY then ORIGIN_CODE_CITY || ' & ' || DEST_CODE_CITY
    else 3 end as [AIRPORT_PAIR]
from main_grouping
--where UNIQUE_CARRIER_NAME in ('1263343 Alberta Inc. d/b/a Lynx Air', 'Porter Airlines, Inc.')
)

select UNIQUE_CARRIER_NAME,
[AIRPORT_PAIR],
SUM(CAST(TOTAL_PASSENGERS as INT)) as [TOTAL PASSENGERS],
SUM(CAST(TOTAL_SEATS as INT)) as [TOTAL SEATS],

(SUM(CAST(TOTAL_PASSENGERS as FLOAT)) / SUM(CAST(TOTAL_SEATS as FLOAT))) * 100.00 as [PASSENGER UTIL PCT],

ROW_NUMBER() OVER (PARTITION BY UNIQUE_CARRIER_NAME order by SUM(CAST(TOTAL_PASSENGERS as INT)) desc) as [PASSENGER RANKING]

from sorting

-- where UNIQUE_CARRIER_NAME like '%Porter%'

group by UNIQUE_CARRIER_NAME,
[AIRPORT_PAIR]

order by UNIQUE_CARRIER_NAME, SUM(CAST(TOTAL_PASSENGERS as INT)) desc;



